<?php

declare(strict_types=1);

namespace NimbusCMS\Blog;

/**
 * Hosts diagram PNGs under the site's public uploads directory, in the plugin's own
 * sub-namespace so it never collides with core media: `<uploads>/<pluginId>/diagrams/
 * <ab>/<hash>.png`, served at `<appUrl><uploadUrl>/<pluginId>/diagrams/<ab>/<hash>.png`.
 * The path is derived only from the content hash (sharded by its first two hex chars),
 * so it is stable and recomputable, which is what makes the file itself the cache.
 *
 * The bytes are generated by the plugin (a rasterized diagram), not an untrusted
 * upload, so this writes the file directly rather than going through the core media
 * pipeline (which plugins cannot reach anyway); the absolute URL is built with the
 * same `appUrl + uploadUrl` convention core uses everywhere it needs one.
 */
final class UploadsDiagramStore implements DiagramStore
{
    public function __construct(
        private string $baseDir,
        private string $urlPrefix,
        private string $appUrl,
        private string $pluginId,
    ) {
    }

    public function has(string $hash): bool
    {
        return is_file($this->baseDir . '/' . $this->relativePath($hash));
    }

    public function url(string $hash): string
    {
        return rtrim($this->appUrl, '/') . '/' . rtrim(trim($this->urlPrefix, '/'), '/') . '/' . $this->relativePath($hash);
    }

    public function store(string $hash, string $png): bool
    {
        $path = $this->baseDir . '/' . $this->relativePath($hash);
        $dir  = dirname($path);
        if (!is_dir($dir) && !@mkdir($dir, 0o755, true) && !is_dir($dir)) {
            return false;
        }
        return @file_put_contents($path, $png) !== false;
    }

    private function relativePath(string $hash): string
    {
        return $this->pluginId . '/diagrams/' . substr($hash, 0, 2) . '/' . $hash . '.png';
    }
}
